config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /zh-TW|en/ do
    devise_for :users, controllers: {:registrations => "users"}

    resources :leave_events do
      member do
        post :verify
        post :reject
      end
    end

    resources :users

    root "welcome#index"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    case user.role
    when "admin"
      can :manage, :all
    when "employee"
      can :create, LeaveEvent
      can :read, LeaveEvent, user_id: user.id
      can :read, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave_event.rb
class LeaveEvent < ApplicationRecord
  belongs_to :user
  before_create :generate_token
  after_save :calculate_hours

  validates_presence_of :start_time, :end_time, :leave_type, :description

  BASIC_TYPES = %i(annual bonus personal sick).freeze
  STATUS = %i(pending approved rejected canceled).freeze

  scope :completed, -> { where.not(status: "pending") }

  def verify(manager)
    return false if manager.nil? && !can_verify?

    update_columns(manager_id: manager.id, status: "approved", sign_date: Time.zone.now)
  end

  def reject(manager)
    return false if manager.nil? && !can_verify?

    update_columns(manager_id: manager.id, status: "rejected", sign_date: Time.zone.now)
  end

  def can_verify?
    status == "pending"
  end

  def generate_token
    self.token = SecureRandom.hex(5).upcase
  end

  def calculate_hours
    update_columns(hours: ((end_time - start_time) / 1.hour).round)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :leave_events

  ROLES = %i(
    manager employee contractor intern resigned pending admin
  ).freeze

  def admin?
    role == 'admin'
  end

  def manager?
    role == 'manager'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_action :set_locale

  protected

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(*)
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  def admin_required
    unless current_user.admin?
      redirect_to "/"
    end
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  helper_method :resource_name, :resource_class, :resource_instance, :collection_instance

  before_action :authenticate_user!

  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  private

  def resource_name
    @resource_name ||= controller_name.singularize.downcase.to_sym
  end

  def resource_class
    resource_instance.class
  end

  def collection_instance_name
    @collection_instance_name ||= "@#{controller_name.downcase}".to_sym
  end

  def resource_instance
    instance_variable_get("@#{resource_name}".to_sym)
  end

  def resource_instance=(instance)
    instance_variable_set("@#{resource_name}".to_sym, instance)
  end

  def collection_instance
    instance_variable_get(collection_instance_name)
  end

  def collection_instance=(instance)
    instance_variable_set(collection_instance_name, instance)
  end
end

app/controllers/leave_events_controller.rb
class LeaveEventsController < BaseController
  skip_load_resource except: [:create, :new]

  def index
    @leave_events = LeaveEvent.where(sign_date: nil)
  end

  def create
    @leave_event = current_user.leave_events.build(leave_event_params)

    if @leave_event.save
      redirect_to leave_events_path, notice: "假單送出成功"
    else
      render :new
    end
  end

  def show
    @leave_event = LeaveEvent.find_by_token(params[:id])
  end

  def verify
    obj = LeaveEvent.find_by_token(params[:id])

    if obj.verify(current_user)
      redirect_to leave_events_path, notice: "審核成功"
    else
      redirect_to leave_events_path, alert: "審核失敗"
    end
  end

  def reject
    obj = LeaveEvent.find_by_token(params[:id])

    if obj.reject(current_user)
      redirect_to leave_events_path, notice: "駁回成功"
    else
      redirect_to leave_events_path, alert: "駁回失敗"
    end
  end

  private

  def leave_event_params
    params.require(:leave_event).permit(
      :start_time, :end_time, :leave_type, :description
    )
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :admin_required, only: :create

  def create
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :role,
      :password, :password_confirmation,
      :join_date
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  def index
    @pending_events = current_user.leave_events.where(status: "pending")
    @completed_events = current_user.leave_events.completed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def t_options(key)
    I18n.t(key, scope: 'select_options', default: '')
  end

  def t_a(key)
    I18n.t(key, scope: 'activerecord.attributes', default: '')
  end

  def t_option_str(key, code)
    t_options("#{key}.#{code}").empty? ? code : t_options("#{key}.#{code}")
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/leave_events_helper.rb
module LeaveEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
    <footer>
         <div class="container">
         
            <div class="copy text-center">
               Copyright 2017 <a href='#'>Pakogi</a>
            </div>
            
         </div>
      </footer>

app/views/common/_navbar.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <!-- Logo -->
        <div class="logo">
          <h1><a href="/">Bonga</a></h1>
        </div>
      </div>
      <div class="col-md-7">
        <div class="navbar navbar-inverse" role="banner">
          <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">多語系 <b class="caret"></b></a>
                <ul class="dropdown-menu animated fadeInUp">
                <li><%= link_to "中文版", :controller => controller.controller_name,
              :action => controller.action_name, :locale => "zh-TW"  %></li>
                <li><%= link_to "English", :controller => controller.controller_name,
              :action => controller.action_name, :locale => "en"  %></li>
                </ul>
              </li>
              <% if !current_user %>
              <li> <%= link_to("註冊", new_user_registration_path) %> </li>
              <li> <%= link_to("登入", new_user_session_path) %> </li>
              <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi, <%= current_user.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu animated fadeInUp">
                  <li> <%= link_to("帳號設定", edit_user_registration_path )%></li>
                  <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                </ul>
              </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_sidebar.html.erb
<% if user_signed_in? %>
<div class="sidebar content-box" style="display: block;">
  <ul class="nav">
    <li>
    <% if can? :create, current_user %>
      <%= link_to '管理員工', users_path %>
    <% end %>
    </li>
    <li>
      <%= link_to '我要請假', new_leave_event_path %>
    </li>
    <li>
      <%= link_to '假單狀態', leave_events_path %>
    </li>
    <li>
      <%= link_to '個人資料', user_path(current_user) %>
    </li>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bonga</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'common/navbar' %>
    <div class="container-fluid">
      <%= render "common/flashes" %>
    </div>
    <div class="page-content">
      <div class="row">
        <div class="col-md-2">
          <%= render 'common/sidebar'%>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'common/footer'%>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bonga</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<body class="login-bg">
<%= render 'common/navbar' %>
<%= render "common/flashes" %>
  <div class="page-content container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/leave_events/index.html.slim
.col-md-12
  .content-box-header
    .panel-title 處理假單
  .content-box-large.box-with-header
    table.table.table-hover
      thead
        tr
          td #
          td status
          td Type
      tbody
        - current_user.leave_events.each do |leave_event|
          tr
            td= link_to leave_event.token, leave_event_path(leave_event.token)
            td= t_option_str('leave_status', leave_event.status)
            td= t_option_str('leave_type', leave_event.leave_type)

app/views/leave_events/new.html.slim
.col-md-12
  .content-box-header
    .panel-title 請假申請表
  .content-box-large.box-with-header
    = simple_form_for @leave_event do |f|
      .row
        .col-md-6
          = f.input :start_time, require: :true, as: :string, input_html: { class: "datepicker" }
        .col-md-6
          = f.input :end_time, require: :true, as: :string, input_html: { class: "datepicker" }
        .col-md-6
          = f.input :description, require: :true
        .col-md-6
          = f.input :leave_type, require: :true, collection: LeaveEvent::BASIC_TYPES, include_blank: false
        .col-md-12
          = f.button :submit

app/views/leave_events/show.html.slim
.col-md-12
  .content-box-header
    .panel-title 假單
  .content-box-large.box-with-header
    = t_a 'leave_event.start_time'
    | ：
    = @leave_event.start_time
    br/
    = t_a 'leave_event.end_time'
    |：
    = @leave_event.end_time
    br/
    = t_a 'leave_event.hours'
    |：
    = @leave_event.hours
    br/
    = t_a 'leave_event.description'
    |：
    = @leave_event.description
    br/
    = t_a 'leave_event.leave_type'
    | ：
    = t_option_str('leave_type', @leave_event.leave_type)
    br/
    - if can? :read, current_user
      - if @leave_event.can_verify?
        = link_to '讓他請假', verify_leave_event_path, method: :post, class: 'btn btn-success', data: { confirm: "是否讓他放假?"}
        = link_to '拒絕請假', reject_leave_event_path, method: :post, class: 'btn btn-danger', data: { confirm: "是否拒絕他請假"}

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.input :name, required: true
  = f.input :email, required: true
  = f.input :join_date, input_html: { value: Time.zone.today}
  - unless @user.new_record?
    = f.input :leave_date, input_html: { value: Time.zone.today}
  = f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length)
  = f.input :password_confirmation, required: true
  = f.input :role, require: :true, collection: User::ROLES
  = f.button :submit

app/views/users/edit.html.slim
= render 'form'

app/views/users/index.html.slim
.col-md-12
  .content-box-header
    .panel-title 管理員工
  .content-box-large.box-with-header
    = link_to '新增員工', new_user_path, class: 'btn btn-primary'
    table.table
      thead
        tr
          th Name
          th Role
          th Join Date
          th Leave Date
          th #
      tbody
        - @users.each do |user|
          tr
            td= user.name
            td= t_option_str('user.role', user.role)
            td= user.join_date
            td= user.leave_date
            td= link_to 'edit', edit_user_path(user)

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
.col-md-12
  .content-box-header
    .panel-title 個人資料
  .content-box-large.box-with-header
    p
      | Name: #{@user.name}
    p
      | Email: #{@user.email}
    p
      | Role: #{@user.role}
    p
      | Join Date: #{@user.join_date}
    p
      | Leave Date: #{@user.leave_date}

app/views/welcome/index.html.slim
.col-md-12
  .content-box-header
    .panel-title 基本資料
  .content-box-large.box-with-header
    | 當前身分：
    = current_user.role
.col-md-12
  .content-box-header
    .panel-title 我的待處理假單
  .content-box-large.box-with-header
    table.table.table-striped
      thead
        tr
          th 假單編號
          th 事由
          th 狀態
      tbody
        - @pending_events.each do |p|
          tr
            td= link_to p.token, leave_event_path(p.token)
            td= t_option_str('leave_type', p.leave_type)
            td= t_option_str('leave_status', p.status)
.col-md-12
  .content-box-header
    .panel-title 我的已處理假單
  .content-box-large.box-with-header
    table.table.table-striped
      thead
        tr
          th 假單編號
          th 事由
          th 狀態
      tbody
        - @completed_events.each do |p|
          tr
            td= link_to p.token, leave_event_path(p.token)
            td= t_option_str('leave_type', p.leave_type)
            td= t_option_str('leave_status', p.status)
.col-md-12
  .content-box-header
    .panel-title 今日休假人員
  .content-box-large.box-with-header